### ISSUE TITLE
The download link doesn't work.

### ISSUE THREAD

**Issue by YueYANG1996** [StonyBrookNLP/PeKo#1]
Hi,

I clicked the link and it says "Sorry, the file you have requested does not exist.", could you fix it? Thank you!

Yue

**Comment by niranjanb** [comment]
Yue 

Thanks for pointing this out. We are looking into this. Will get back to you as soon as we are able to recover the data.

**Comment by in2uitive** [comment]
Yue,

Sorry for the inconvenience. The link is fixed now.
